// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.182
// </auto-generated>
// ------------------------------------------------------------------------------
namespace MSTest2XUnit
{
    static class Vsix
    {
        public const string Id = "dd067b6f-96bd-4d0d-be4b-cd0d62fc66b8";
        public const string Name = "MSTest2XUnit";
        public const string Description = "This extension allows to migrate a test suite written with MSTest to XUnit.net 2. It is based on https://github.com/dotnet/codeformatter with some additional converters. The dotnet converter didn't remove some elements and were letting too much manual refactoring that could have still been automated.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Karim ADALA";
        public const string Tags = "mstest, xunit, converter";
    }
}
