// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.182
// </auto-generated>
// ------------------------------------------------------------------------------
namespace MSTest2XUnit
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidMSTest2XUnitCommandPackageString = "7274ca09-e9f5-406b-bab7-eb23c1969e4b";
        public const string guidMSTest2XUnitCommandPackageCmdSetString = "8fdde5ef-0eba-404b-b40a-962e31969775";
        public const string guidImagesString = "d8359279-256e-4ad4-9e64-e644bdb8fa15";
        public static Guid guidMSTest2XUnitCommandPackage = new Guid(guidMSTest2XUnitCommandPackageString);
        public static Guid guidMSTest2XUnitCommandPackageCmdSet = new Guid(guidMSTest2XUnitCommandPackageCmdSetString);
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MSTest2XUnitGroup = 0x1020;
        public const int MSTest2XUnitCommandId = 0x0100;
        public const int bmpPic1 = 0x0001;
    }
}
